// ─────────────────────────────────────────────────────────────────────────────
// Lift Trainer App — Demo Data (Kerala Fitness Context)
// Used for client presentations — no real API needed
// ─────────────────────────────────────────────────────────────────────────────

import {
  TrainerProfile,
  TrainerDashboard,
  ClientCard,
  ClientProfile,
  WorkoutPlan,
  WorkoutLog,
  TrainerVideo,
  LiveClass,
  WeightEntry,
  BodyMeasurement,
  ProgressPhoto,
  FreelanceInvite,
  TrainerEarnings,
  FeeDue,
  PaymentRecord,
  TrainerNotification,
  Certification,
} from '../types/trainer.types';

// ─── Logged-in Trainer ───────────────────────────────────────────────────────

export const DEMO_TRAINER_ID = 'trainer-demo-001';
export const DEMO_TOKEN = 'demo-token';

export const demoTrainerProfile: TrainerProfile = {
  id: DEMO_TRAINER_ID,
  fullName: 'Arun Krishnan',
  phone: '9876543210',
  age: 32,
  gender: 'Male',
  profilePhotoUrl: null,
  specializations: ['Weight Training', 'HIIT', 'Strength', 'Nutrition Coaching'],
  yearsOfExperience: 8,
  bio: 'Certified strength and conditioning coach with 8 years of experience training athletes and fitness enthusiasts across Kerala. Passionate about helping people achieve their best physical potential.',
  isLifeVerified: true,
  gymId: 'gym-001',
  gymName: 'FitZone Gym',
  gymAddress: 'Near Palarivattom Junction, Ernakulam, Kerala 682025',
  isFreelance: true,
  freelanceMonthlyFee: 2500,
  acceptingNewClients: true,
  certifications: [
    {
      id: 'cert-1',
      name: 'NSCA Certified Strength & Conditioning Specialist',
      imageUrl: '',
      status: 'Lift-Verified',
      uploadedAt: '2023-06-15T00:00:00Z',
    },
    {
      id: 'cert-2',
      name: 'Precision Nutrition Level 1',
      imageUrl: '',
      status: 'Lift-Verified',
      uploadedAt: '2023-09-20T00:00:00Z',
    },
    {
      id: 'cert-3',
      name: 'CPR & First Aid Certified',
      imageUrl: '',
      status: 'Pending Review',
      uploadedAt: '2025-01-10T00:00:00Z',
    },
  ],
  availabilityHours: {
    monday: { isAvailable: true, startTime: '06:00', endTime: '21:00' },
    tuesday: { isAvailable: true, startTime: '06:00', endTime: '21:00' },
    wednesday: { isAvailable: true, startTime: '06:00', endTime: '21:00' },
    thursday: { isAvailable: true, startTime: '06:00', endTime: '21:00' },
    friday: { isAvailable: true, startTime: '06:00', endTime: '21:00' },
    saturday: { isAvailable: true, startTime: '07:00', endTime: '14:00' },
    sunday: { isAvailable: false },
  },
};

// ─── Dashboard ───────────────────────────────────────────────────────────────

export const demoDashboard: TrainerDashboard = {
  todaySchedule: [
    {
      clientId: 'member-001',
      clientName: 'Rahul Menon',
      clientPhotoUrl: null,
      planName: 'Strength Builder - 8 Week',
      lastWorkoutStatus: 'completed',
    },
    {
      clientId: 'member-002',
      clientName: 'Priya Nair',
      clientPhotoUrl: null,
      planName: 'Fat Loss Accelerator',
      lastWorkoutStatus: 'incomplete',
    },
    {
      clientId: 'member-003',
      clientName: 'Vishnu Pillai',
      clientPhotoUrl: null,
      planName: 'Athletic Performance',
      lastWorkoutStatus: 'not_started',
    },
    {
      clientId: 'member-004',
      clientName: 'Anjali Thomas',
      clientPhotoUrl: null,
      planName: 'Beginner Fitness',
      lastWorkoutStatus: 'completed',
    },
  ],
  recentActivity: [
    {
      clientId: 'member-001',
      clientName: 'Rahul Menon',
      clientPhotoUrl: null,
      workoutName: 'Day 3 - Push Day',
      status: 'completed',
      timeAgo: '2h ago',
      logId: 'log-001',
    },
    {
      clientId: 'member-004',
      clientName: 'Anjali Thomas',
      clientPhotoUrl: null,
      workoutName: 'Day 1 - Full Body',
      status: 'completed',
      timeAgo: '4h ago',
      logId: 'log-002',
    },
    {
      clientId: 'member-002',
      clientName: 'Priya Nair',
      clientPhotoUrl: null,
      workoutName: 'Day 5 - Cardio & Core',
      status: 'incomplete',
      timeAgo: '6h ago',
      logId: 'log-003',
    },
    {
      clientId: 'member-005',
      clientName: 'Sreejith Kumar',
      clientPhotoUrl: null,
      workoutName: 'Day 2 - Pull Day',
      status: 'completed',
      timeAgo: 'Yesterday',
      logId: 'log-004',
    },
    {
      clientId: 'member-006',
      clientName: 'Divya Chandran',
      clientPhotoUrl: null,
      workoutName: 'Day 4 - Legs',
      status: 'completed',
      timeAgo: 'Yesterday',
      logId: 'log-005',
    },
  ],
  pendingActions: {
    clientsWithoutPlan: 2,
    missedWorkouts: 3,
    feeDue: 1,
  },
  quickStats: {
    totalActiveClients: 12,
    sessionsThisWeek: 34,
    unreadLogs: 5,
  },
  earningsSummary: {
    thisMonthTotal: 38500,
    gymSalary: 25000,
    freelanceFees: 13500,
  },
};

// ─── Client List ─────────────────────────────────────────────────────────────

export const demoClients: ClientCard[] = [
  {
    id: 'member-001',
    fullName: 'Rahul Menon',
    profilePhotoUrl: null,
    membershipStatus: 'Active',
    lastWorkoutDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    assignedPlanName: 'Strength Builder - 8 Week',
    streak: 14,
    hasRiskFlag: false,
    clientType: 'gym',
  },
  {
    id: 'member-002',
    fullName: 'Priya Nair',
    profilePhotoUrl: null,
    membershipStatus: 'Active',
    lastWorkoutDate: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    assignedPlanName: 'Fat Loss Accelerator',
    streak: 7,
    hasRiskFlag: false,
    clientType: 'gym',
  },
  {
    id: 'member-003',
    fullName: 'Vishnu Pillai',
    profilePhotoUrl: null,
    membershipStatus: 'Expiring',
    lastWorkoutDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    assignedPlanName: 'Athletic Performance',
    streak: 0,
    hasRiskFlag: true,
    clientType: 'gym',
  },
  {
    id: 'member-004',
    fullName: 'Anjali Thomas',
    profilePhotoUrl: null,
    membershipStatus: 'Active',
    lastWorkoutDate: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    assignedPlanName: 'Beginner Fitness',
    streak: 21,
    hasRiskFlag: false,
    clientType: 'gym',
  },
  {
    id: 'member-005',
    fullName: 'Sreejith Kumar',
    profilePhotoUrl: null,
    membershipStatus: 'Active',
    lastWorkoutDate: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    assignedPlanName: 'Hypertrophy Program',
    streak: 9,
    hasRiskFlag: false,
    clientType: 'gym',
  },
  {
    id: 'member-006',
    fullName: 'Divya Chandran',
    profilePhotoUrl: null,
    membershipStatus: 'Active',
    lastWorkoutDate: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    assignedPlanName: 'Tone & Strengthen',
    streak: 5,
    hasRiskFlag: false,
    clientType: 'gym',
  },
  {
    id: 'member-007',
    fullName: 'Arjun Varma',
    profilePhotoUrl: null,
    membershipStatus: 'Expired',
    lastWorkoutDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    assignedPlanName: null,
    streak: 0,
    hasRiskFlag: true,
    clientType: 'gym',
  },
  // Freelance clients
  {
    id: 'member-008',
    fullName: 'Meera Suresh',
    profilePhotoUrl: null,
    membershipStatus: 'Active',
    lastWorkoutDate: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    assignedPlanName: 'Post-Pregnancy Recovery',
    streak: 11,
    hasRiskFlag: false,
    clientType: 'freelance',
  },
  {
    id: 'member-009',
    fullName: 'Nikhil George',
    profilePhotoUrl: null,
    membershipStatus: 'Active',
    lastWorkoutDate: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    assignedPlanName: 'CEO Fitness Program',
    streak: 3,
    hasRiskFlag: false,
    clientType: 'freelance',
  },
  {
    id: 'member-010',
    fullName: 'Lakshmi Iyer',
    profilePhotoUrl: null,
    membershipStatus: 'Active',
    lastWorkoutDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    assignedPlanName: 'Yoga & Strength Fusion',
    streak: 0,
    hasRiskFlag: true,
    clientType: 'freelance',
  },
];

// ─── Client Profiles ──────────────────────────────────────────────────────────

export const demoClientProfiles: Record<string, ClientProfile> = {
  'member-001': {
    id: 'member-001',
    fullName: 'Rahul Menon',
    profilePhotoUrl: null,
    age: 28,
    gender: 'Male',
    phone: '9845671234',
    healthGoals: ['Build Muscle', 'Increase Strength', 'Improve Posture'],
    membershipStatus: 'Active',
    currentPlanName: 'Strength Builder - 8 Week',
    planAssignedDate: '2026-02-01T00:00:00Z',
    latestWeight: 74,
    latestBMI: 23.1,
    lastWorkoutDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    totalWorkoutsLogged: 38,
    currentStreak: 14,
    attendanceThisMonth: 22,
    clientType: 'gym',
  },
  'member-002': {
    id: 'member-002',
    fullName: 'Priya Nair',
    profilePhotoUrl: null,
    age: 26,
    gender: 'Female',
    phone: '9745612345',
    healthGoals: ['Weight Loss', 'Improve Endurance', 'Reduce Stress'],
    membershipStatus: 'Active',
    currentPlanName: 'Fat Loss Accelerator',
    planAssignedDate: '2026-01-15T00:00:00Z',
    latestWeight: 62,
    latestBMI: 24.2,
    lastWorkoutDate: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    totalWorkoutsLogged: 29,
    currentStreak: 7,
    attendanceThisMonth: 18,
    clientType: 'gym',
  },
  'member-003': {
    id: 'member-003',
    fullName: 'Vishnu Pillai',
    profilePhotoUrl: null,
    age: 22,
    gender: 'Male',
    phone: '9567891234',
    healthGoals: ['Athletic Performance', 'Speed & Agility', 'Injury Prevention'],
    membershipStatus: 'Expiring',
    currentPlanName: 'Athletic Performance',
    planAssignedDate: '2025-12-01T00:00:00Z',
    latestWeight: 68,
    latestBMI: 21.8,
    lastWorkoutDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    totalWorkoutsLogged: 15,
    currentStreak: 0,
    attendanceThisMonth: 9,
    clientType: 'gym',
  },
  'member-004': {
    id: 'member-004',
    fullName: 'Anjali Thomas',
    profilePhotoUrl: null,
    age: 34,
    gender: 'Female',
    phone: '9812345678',
    healthGoals: ['General Fitness', 'Flexibility', 'Energy Levels'],
    membershipStatus: 'Active',
    currentPlanName: 'Beginner Fitness',
    planAssignedDate: '2026-02-10T00:00:00Z',
    latestWeight: 58,
    latestBMI: 22.5,
    lastWorkoutDate: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    totalWorkoutsLogged: 42,
    currentStreak: 21,
    attendanceThisMonth: 24,
    clientType: 'gym',
  },
  'member-008': {
    id: 'member-008',
    fullName: 'Meera Suresh',
    profilePhotoUrl: null,
    age: 31,
    gender: 'Female',
    phone: '9645781234',
    healthGoals: ['Post-Pregnancy Recovery', 'Core Strength', 'Healthy Weight'],
    membershipStatus: 'Active',
    currentPlanName: 'Post-Pregnancy Recovery',
    planAssignedDate: '2026-01-20T00:00:00Z',
    latestWeight: 64,
    latestBMI: 23.8,
    lastWorkoutDate: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    totalWorkoutsLogged: 24,
    currentStreak: 11,
    attendanceThisMonth: 20,
    clientType: 'freelance',
  },
};

// ─── Workout Logs ─────────────────────────────────────────────────────────────

export const demoWorkoutLogs: WorkoutLog[] = [
  {
    id: 'log-001',
    memberId: 'member-001',
    memberName: 'Rahul Menon',
    memberPhotoUrl: null,
    planName: 'Strength Builder - 8 Week',
    dayLabel: 'Day 3 - Push Day',
    completedExercises: [
      { exerciseId: 'e1', exerciseName: 'Bench Press', actualSets: 4, actualReps: '8', completed: true },
      { exerciseId: 'e2', exerciseName: 'Overhead Press', actualSets: 3, actualReps: '10', completed: true },
      { exerciseId: 'e3', exerciseName: 'Incline Dumbbell Press', actualSets: 3, actualReps: '12', completed: true },
      { exerciseId: 'e4', exerciseName: 'Tricep Pushdown', actualSets: 3, actualReps: '15', completed: true },
      { exerciseId: 'e5', exerciseName: 'Lateral Raises', actualSets: 3, actualReps: '15', completed: false },
    ],
    status: 'completed',
    loggedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    trainerNote: 'Great session! Bench press form was solid. Try adding 2.5kg next week.',
  },
  {
    id: 'log-002',
    memberId: 'member-001',
    memberName: 'Rahul Menon',
    memberPhotoUrl: null,
    planName: 'Strength Builder - 8 Week',
    dayLabel: 'Day 2 - Pull Day',
    completedExercises: [
      { exerciseId: 'e6', exerciseName: 'Deadlift', actualSets: 4, actualReps: '6', completed: true },
      { exerciseId: 'e7', exerciseName: 'Barbell Row', actualSets: 3, actualReps: '8', completed: true },
      { exerciseId: 'e8', exerciseName: 'Pull-ups', actualSets: 3, actualReps: '6', completed: true },
      { exerciseId: 'e9', exerciseName: 'Face Pulls', actualSets: 3, actualReps: '15', completed: true },
      { exerciseId: 'e10', exerciseName: 'Bicep Curls', actualSets: 3, actualReps: '12', completed: true },
    ],
    status: 'completed',
    loggedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log-003',
    memberId: 'member-001',
    memberName: 'Rahul Menon',
    memberPhotoUrl: null,
    planName: 'Strength Builder - 8 Week',
    dayLabel: 'Day 1 - Legs',
    completedExercises: [
      { exerciseId: 'e11', exerciseName: 'Back Squat', actualSets: 4, actualReps: '8', completed: true },
      { exerciseId: 'e12', exerciseName: 'Romanian Deadlift', actualSets: 3, actualReps: '10', completed: true },
      { exerciseId: 'e13', exerciseName: 'Leg Press', actualSets: 3, actualReps: '12', completed: false },
      { exerciseId: 'e14', exerciseName: 'Calf Raises', actualSets: 4, actualReps: '20', completed: false },
    ],
    status: 'incomplete',
    loggedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Video Library ────────────────────────────────────────────────────────────

export const demoVideos: TrainerVideo[] = [
  {
    id: 'vid-001',
    title: 'Perfect Squat Form — Common Mistakes Fixed',
    description: 'Learn the 5 most common squat mistakes and how to correct them for maximum muscle activation and injury prevention.',
    category: 'Technique',
    thumbnailUrl: '',
    videoUrl: '',
    durationSeconds: 847,
    uploadedAt: '2026-02-10T00:00:00Z',
    isPersonalized: false,
  },
  {
    id: 'vid-002',
    title: 'Upper Body Warm-Up Routine — 10 Minutes',
    description: 'Full upper body activation routine. Do this before every push or pull session.',
    category: 'Warm-Up',
    thumbnailUrl: '',
    videoUrl: '',
    durationSeconds: 612,
    uploadedAt: '2026-02-05T00:00:00Z',
    isPersonalized: false,
  },
  {
    id: 'vid-003',
    title: 'HIIT Fat Burner — 20 Minute Session',
    description: 'High intensity interval training circuit. 40 seconds on, 20 seconds rest. No equipment needed.',
    category: 'Cardio',
    thumbnailUrl: '',
    videoUrl: '',
    durationSeconds: 1215,
    uploadedAt: '2026-01-28T00:00:00Z',
    isPersonalized: false,
  },
  {
    id: 'vid-004',
    title: 'Deadlift Masterclass — From Zero to Heavy',
    description: 'Complete guide to the conventional deadlift. Setup, execution, and programming advice.',
    category: 'Technique',
    thumbnailUrl: '',
    videoUrl: '',
    durationSeconds: 1432,
    uploadedAt: '2026-01-20T00:00:00Z',
    isPersonalized: false,
  },
  {
    id: 'vid-005',
    title: 'Rahul — Week 6 Check-in & Form Correction',
    description: 'Personal feedback on your bench press and overhead press form. Focus points for next 2 weeks.',
    category: 'Technique',
    thumbnailUrl: '',
    videoUrl: '',
    durationSeconds: 432,
    uploadedAt: '2026-03-10T00:00:00Z',
    isPersonalized: true,
    assignedMemberId: 'member-001',
    assignedMemberName: 'Rahul Menon',
    watchStatus: 'watched',
    watchedPercent: 100,
  },
  {
    id: 'vid-006',
    title: 'Meera — Postpartum Core Activation Guide',
    description: 'Safe and effective core exercises specifically for your recovery phase. Start with Level 1 this week.',
    category: 'Core',
    thumbnailUrl: '',
    videoUrl: '',
    durationSeconds: 763,
    uploadedAt: '2026-03-12T00:00:00Z',
    isPersonalized: true,
    assignedMemberId: 'member-008',
    assignedMemberName: 'Meera Suresh',
    watchStatus: 'in_progress',
    watchedPercent: 45,
    expiresAt: '2026-04-12T00:00:00Z',
  },
];

// ─── Live Classes ─────────────────────────────────────────────────────────────

export const demoUpcomingClasses: LiveClass[] = [
  {
    id: 'class-001',
    trainerId: DEMO_TRAINER_ID,
    gymId: 'gym-001',
    name: 'Morning Strength Circuit',
    category: 'Strength',
    scheduledAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    durationMinutes: 45,
    maxParticipants: 20,
    rsvpCount: 14,
    description: 'Full body strength circuit using compound movements. All levels welcome.',
    recordSession: true,
    status: 'Scheduled',
  },
  {
    id: 'class-002',
    trainerId: DEMO_TRAINER_ID,
    gymId: 'gym-001',
    name: 'Evening HIIT Blast',
    category: 'Cardio',
    scheduledAt: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    durationMinutes: 30,
    maxParticipants: 25,
    rsvpCount: 19,
    description: 'High intensity cardio session. Bring water and a towel!',
    recordSession: false,
    status: 'Scheduled',
  },
  {
    id: 'class-003',
    trainerId: DEMO_TRAINER_ID,
    gymId: 'gym-001',
    name: 'Mobility & Flexibility Flow',
    category: 'Mobility',
    scheduledAt: new Date(Date.now() + 50 * 60 * 60 * 1000).toISOString(),
    durationMinutes: 60,
    maxParticipants: 15,
    rsvpCount: 8,
    description: 'Deep stretching and mobility work. Perfect for recovery days.',
    recordSession: true,
    status: 'Scheduled',
  },
];

export const demoPastClasses: LiveClass[] = [
  {
    id: 'class-p01',
    trainerId: DEMO_TRAINER_ID,
    gymId: 'gym-001',
    name: 'Saturday Power Session',
    category: 'Strength',
    scheduledAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    durationMinutes: 60,
    maxParticipants: 20,
    rsvpCount: 17,
    description: '',
    recordSession: true,
    status: 'Completed',
    averageRating: 4.8,
    recordingUrl: 'https://demo-recording.url',
  },
  {
    id: 'class-p02',
    trainerId: DEMO_TRAINER_ID,
    gymId: 'gym-001',
    name: 'Core Conditioning',
    category: 'Strength',
    scheduledAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    durationMinutes: 45,
    maxParticipants: 15,
    rsvpCount: 12,
    description: '',
    recordSession: false,
    status: 'Completed',
    averageRating: 4.6,
  },
];

// ─── Weight & BMI ─────────────────────────────────────────────────────────────

export const demoWeightHistory: WeightEntry[] = [
  { date: '2026-03-15', weightKg: 74.0, bmi: 23.1, trainerAnnotation: 'Looking strong! Maintain this trajectory.' },
  { date: '2026-03-08', weightKg: 74.5, bmi: 23.3 },
  { date: '2026-03-01', weightKg: 75.2, bmi: 23.5 },
  { date: '2026-02-22', weightKg: 75.8, bmi: 23.7 },
  { date: '2026-02-15', weightKg: 76.4, bmi: 23.9 },
  { date: '2026-02-08', weightKg: 77.1, bmi: 24.1 },
  { date: '2026-02-01', weightKg: 77.8, bmi: 24.4, trainerAnnotation: 'Starting Strength Builder program today.' },
  { date: '2026-01-25', weightKg: 78.2, bmi: 24.5 },
  { date: '2026-01-18', weightKg: 78.9, bmi: 24.7 },
  { date: '2026-01-11', weightKg: 79.5, bmi: 24.9 },
];

export const demoMeasurements: BodyMeasurement[] = [
  {
    date: '2026-03-01',
    chestCm: 98,
    waistCm: 82,
    hipsCm: 96,
    armsLeftCm: 35,
    armsRightCm: 35.5,
    thighsLeftCm: 56,
    thighsRightCm: 56,
    calfLeftCm: 37,
    calfRightCm: 37,
  },
  {
    date: '2026-02-01',
    chestCm: 96,
    waistCm: 85,
    hipsCm: 97,
    armsLeftCm: 33,
    armsRightCm: 33.5,
    thighsLeftCm: 57,
    thighsRightCm: 57,
    calfLeftCm: 36,
    calfRightCm: 36,
  },
  {
    date: '2026-01-01',
    chestCm: 94,
    waistCm: 88,
    hipsCm: 98,
    armsLeftCm: 32,
    armsRightCm: 32,
    thighsLeftCm: 58,
    thighsRightCm: 58,
    calfLeftCm: 35.5,
    calfRightCm: 35.5,
  },
];

export const demoProgressPhotos: ProgressPhoto[] = [
  {
    id: 'photo-001',
    date: '2026-03-01',
    photoUrl: '',
    caption: 'Week 8 check-in — front pose',
    trainerComment: 'Great progress on shoulder width! The definition is coming through clearly.',
    isSharedWithTrainer: true,
  },
  {
    id: 'photo-002',
    date: '2026-02-01',
    photoUrl: '',
    caption: 'Week 4 check-in',
    isSharedWithTrainer: true,
  },
  {
    id: 'photo-003',
    date: '2026-01-01',
    photoUrl: '',
    caption: 'Before photo — Day 1',
    isSharedWithTrainer: true,
  },
];

// ─── Freelance Invites ────────────────────────────────────────────────────────

export const demoFreelanceInvites: FreelanceInvite[] = [
  {
    id: 'invite-001',
    inviteCode: 'ARUN2026A',
    inviteLink: 'https://lift.app/trainer/invite/ARUN2026A',
    monthlyFee: 2500,
    startDate: '2026-03-01T00:00:00Z',
    status: 'Accepted',
    createdAt: '2026-02-20T00:00:00Z',
    expiresAt: '2026-02-27T00:00:00Z',
    clientName: 'Meera Suresh',
    clientId: 'member-008',
  },
  {
    id: 'invite-002',
    inviteCode: 'ARUN2026B',
    inviteLink: 'https://lift.app/trainer/invite/ARUN2026B',
    monthlyFee: 3000,
    startDate: '2026-03-01T00:00:00Z',
    status: 'Accepted',
    createdAt: '2026-02-22T00:00:00Z',
    expiresAt: '2026-03-01T00:00:00Z',
    clientName: 'Nikhil George',
    clientId: 'member-009',
  },
  {
    id: 'invite-003',
    inviteCode: 'ARUN2026C',
    inviteLink: 'https://lift.app/trainer/invite/ARUN2026C',
    monthlyFee: 2000,
    startDate: '2026-03-15T00:00:00Z',
    status: 'Pending',
    createdAt: '2026-03-08T00:00:00Z',
    expiresAt: '2026-03-15T00:00:00Z',
  },
  {
    id: 'invite-004',
    inviteCode: 'ARUN2026D',
    inviteLink: 'https://lift.app/trainer/invite/ARUN2026D',
    monthlyFee: 2500,
    startDate: '2026-02-15T00:00:00Z',
    status: 'Expired',
    createdAt: '2026-02-08T00:00:00Z',
    expiresAt: '2026-02-15T00:00:00Z',
  },
];

// ─── Earnings ─────────────────────────────────────────────────────────────────

export const demoEarnings: TrainerEarnings = {
  month: '2026-03',
  totalReceived: 38500,
  pendingPayouts: 5500,
  thisYearTotal: 98000,
  gymSalary: 25000,
  freelanceFees: 13500,
  sessionBonuses: 0,
  monthlyTrend: [
    { month: 'Oct 2025', gymSalary: 25000, freelanceFees: 5000, total: 30000 },
    { month: 'Nov 2025', gymSalary: 25000, freelanceFees: 7500, total: 32500 },
    { month: 'Dec 2025', gymSalary: 25000, freelanceFees: 8000, total: 33000 },
    { month: 'Jan 2026', gymSalary: 25000, freelanceFees: 10000, total: 35000 },
    { month: 'Feb 2026', gymSalary: 25000, freelanceFees: 11000, total: 36000 },
    { month: 'Mar 2026', gymSalary: 25000, freelanceFees: 13500, total: 38500 },
  ],
};

export const demoFeeDues: FeeDue[] = [
  {
    clientId: 'member-010',
    clientName: 'Lakshmi Iyer',
    clientPhone: '9812340987',
    amountDue: 2000,
    daysOverdue: 12,
    paymentLink: 'https://razorpay.com/demo-link',
  },
];

export const demoPaymentHistory: PaymentRecord[] = [
  {
    id: 'pay-001',
    date: '2026-03-01T00:00:00Z',
    clientName: 'Meera Suresh',
    amount: 2500,
    description: 'Monthly subscription — March 2026',
    status: 'Received',
    receiptUrl: 'https://demo-receipt.pdf',
    payoutDate: '2026-03-03T00:00:00Z',
  },
  {
    id: 'pay-002',
    date: '2026-03-01T00:00:00Z',
    clientName: 'Nikhil George',
    amount: 3000,
    description: 'Monthly subscription — March 2026',
    status: 'Received',
    receiptUrl: 'https://demo-receipt.pdf',
    payoutDate: '2026-03-03T00:00:00Z',
  },
  {
    id: 'pay-003',
    date: '2026-03-01T00:00:00Z',
    clientName: 'Gym Salary — FitZone',
    amount: 25000,
    description: 'Monthly gym salary — March 2026',
    status: 'Received',
  },
  {
    id: 'pay-004',
    date: '2026-02-28T00:00:00Z',
    clientName: 'Lakshmi Iyer',
    amount: 2000,
    description: 'Monthly subscription — March 2026',
    status: 'Pending',
  },
  {
    id: 'pay-005',
    date: '2026-02-01T00:00:00Z',
    clientName: 'Meera Suresh',
    amount: 2500,
    description: 'Monthly subscription — February 2026',
    status: 'Received',
    receiptUrl: 'https://demo-receipt.pdf',
  },
  {
    id: 'pay-006',
    date: '2026-02-01T00:00:00Z',
    clientName: 'Gym Salary — FitZone',
    amount: 25000,
    description: 'Monthly gym salary — February 2026',
    status: 'Received',
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────

export const demoNotifications: TrainerNotification[] = [
  {
    id: 'notif-001',
    type: 'workout_logged',
    title: 'Workout Logged',
    body: 'Rahul Menon completed Day 3 - Push Day',
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    clientId: 'member-001',
    clientName: 'Rahul Menon',
    deeplink: '/clients/member-001/logs',
  },
  {
    id: 'notif-002',
    type: 'workout_logged',
    title: 'Workout Logged',
    body: 'Anjali Thomas completed Day 1 - Full Body',
    isRead: false,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    clientId: 'member-004',
    clientName: 'Anjali Thomas',
  },
  {
    id: 'notif-003',
    type: 'video_watched',
    title: 'Video Watched',
    body: 'Rahul Menon watched your personal video — Week 6 Check-in',
    isRead: false,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    clientId: 'member-001',
    clientName: 'Rahul Menon',
  },
  {
    id: 'notif-004',
    type: 'class_rsvp',
    title: 'Class RSVP',
    body: '14 members have RSVPed for Morning Strength Circuit tomorrow',
    isRead: true,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-005',
    type: 'payment_received',
    title: 'Payment Received',
    body: 'Meera Suresh paid ₹2,500 for March subscription',
    isRead: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    clientId: 'member-008',
    clientName: 'Meera Suresh',
  },
  {
    id: 'notif-006',
    type: 'membership_due',
    title: 'Fee Due',
    body: 'Lakshmi Iyer — ₹2,000 subscription fee is 12 days overdue',
    isRead: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    clientId: 'member-010',
    clientName: 'Lakshmi Iyer',
  },
  {
    id: 'notif-007',
    type: 'client_invited_accepted',
    title: 'New Client',
    body: 'Nikhil George accepted your invite and is now your client!',
    isRead: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    clientId: 'member-009',
    clientName: 'Nikhil George',
  },
  {
    id: 'notif-008',
    type: 'workout_logged',
    title: 'Workout Logged',
    body: 'Meera Suresh completed Post-Pregnancy Core — Week 3',
    isRead: true,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    clientId: 'member-008',
    clientName: 'Meera Suresh',
  },
];
